version: '3.1'

services:
    pywps:
        image: pywps/gunicorn-alpine:latest
    nginx:
        image: pywps/nginx-alpine:latest
        build: .
        depends_on:
            - pywps
        ports:
            - 80:80
        links:
            - pywps
